id: PF67B6694
initial_creation_type: input
source_metadata:
  title: Prajñāpāramitāhṛdayasūtra
  language: sa
  volumes:
    c36eb4e836754e9eaf47318d64415ce5:
      title: Complete text
      base_file: Complete text.txt
      work_id: W5C7D799A
  chapter_to_tile: {}
created_at: '2022-03-02T08:59:35.802618'
last_modified_at: '2022-03-02T08:59:35.802626'
